In [4]:
import torch
from torch import nn
from tqdm.auto import tqdm
from torchvision import transforms
from torchvision.datasets import MNIST # Training dataset
from torchvision.utils import make_grid
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
torch.manual_seed(0) # Set for testing purposes, please do not change!

def show_tensor_images(image_tensor, num_images=25, size=(1, 28, 28)):
    '''
    Function for visualizing images: Given a tensor of images, number of images, and
    size per image, plots and prints the images in a uniform grid.
    '''
    image_unflat = image_tensor.detach().cpu().view(-1, *size)
    image_grid = make_grid(image_unflat[:num_images], nrow=5)
    plt.imshow(image_grid.permute(1, 2, 0).squeeze())
    plt.show()

In [9]:
aa= torch.arange(1,3)
torch.dot (aa, torch.arange(3,5))

tensor(11)

In [29]:
in_height, in_width = data.shape[-2:]
device, num_sizes, num_ratios = data.device, len(sizes), len(ratios)
boxes_per_pixel = (num_sizes + num_ratios - 1)
size_tensor = torch.tensor(sizes, device=device)
ratio_tensor = torch.tensor(ratios, device=device)

# 为了将锚点移动到像素的中心，需要设置偏移量。
# 因为一个像素的的高为1且宽为1，我们选择偏移我们的中心0.5
offset_h, offset_w = 0.5, 0.5
steps_h = 1.0 / in_height  # Scaled steps in y axis
steps_w = 1.0 / in_width  # Scaled steps in x axis

# 生成锚框的所有中心点
center_h = (torch.arange(in_height, device=device) + offset_h) * steps_h
center_w = (torch.arange(in_width, device=device) + offset_w) * steps_w
shift_y, shift_x = torch.meshgrid(center_h, center_w)
shift_y, shift_x = shift_y.reshape(-1), shift_x.reshape(-1)

# 生成“boxes_per_pixel”个高和宽，
# 之后用于创建锚框的四角坐标 (xmin, xmax, ymin, ymax)
w = torch.cat((size_tensor * torch.sqrt(ratio_tensor[0]),
                sizes[0] * torch.sqrt(ratio_tensor[1:])))\
                * in_height / in_width  # Handle rectangular inputs
h = torch.cat((size_tensor / torch.sqrt(ratio_tensor[0]),
                sizes[0] / torch.sqrt(ratio_tensor[1:])))
# 除以2来获得半高和半宽
anchor_manipulations = torch.stack((-w, -h, w, h)).T.repeat(
                                    in_height * in_width, 1) / 2

<ipython-input-29-d6aa6a58625c>:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  size_tensor = torch.tensor(sizes, device=device)
<ipython-input-29-d6aa6a58625c>:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  ratio_tensor = torch.tensor(ratios, device=device)


In [31]:
anchor_manipulations[:10,:]

tensor([[-0.1000, -0.2000,  0.1000,  0.2000],
        [-0.1500, -0.3000,  0.1500,  0.3000],
        [-0.2000, -0.4000,  0.2000,  0.4000],
        [-0.0775, -0.2582,  0.0775,  0.2582],
        [-0.1183, -0.1690,  0.1183,  0.1690],
        [-0.1000, -0.2000,  0.1000,  0.2000],
        [-0.1500, -0.3000,  0.1500,  0.3000],
        [-0.2000, -0.4000,  0.2000,  0.4000],
        [-0.0775, -0.2582,  0.0775,  0.2582],
        [-0.1183, -0.1690,  0.1183,  0.1690]])

In [32]:
anchor_manipulations.shape

torch.Size([100000, 4])

In [26]:
a = torch.tensor([1,2])
a.repeat(2,3,4)

tensor([[[1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2]],

        [[1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2]]])

In [33]:
shift_x=torch.tensor([1,1,1,2,2,2,3,3,3])
shift_y=torch.tensor([1,2,3,1,2,3,1,2,3])
torch.stack([shift_x, shift_y],dim=1)

tensor([[1, 1, 1, 1],
        [1, 2, 1, 2],
        [1, 3, 1, 3],
        [2, 1, 2, 1],
        [2, 2, 2, 2],
        [2, 3, 2, 3],
        [3, 1, 3, 1],
        [3, 2, 3, 2],
        [3, 3, 3, 3]])