In [9]:
from pathlib import Path
import torch
import time

In [18]:
torch.device('cuda:0' if torch.cuda.is_available() else 'cpu') 

'2021-08-20(02.08)'

In [ ]:
os.makedirs("images", exist_ok=True)

parser = argparse.ArgumentParser()
parser.add_argument("--n_epochs", type=int, default=100, help="number of epochs of training")
parser.add_argument("--batch_size", type=int, default=128, help="size of the batches")
parser.add_argument("--lr", type=float, default=0.0002, help="adam: learning rate")
parser.add_argument("--b1", type=float, default=0.5, help="adam: decay of first order momentum of gradient")
parser.add_argument("--b2", type=float, default=0.999, help="adam: decay of first order momentum of gradient")
parser.add_argument("--n_cpu", type=int, default=8, help="number of cpu threads to use during batch generation")
parser.add_argument("--latent_dim", type=int, default=100, help="dimensionality of the latent space")
parser.add_argument("--img_size", type=int, default=28, help="size of each image dimension")
parser.add_argument("--channels", type=int, default=1, help="number of image channels")
parser.add_argument("--sample_interval", type=int, default=400, help="interval betwen image samples")
opt = parser.parse_args()
print(opt)

In [46]:
feature_map = torch.ones((1))                                                    # 1D
feature_maps = torch.stack([feature_map*(i+1) for i in range(5)], dim=0) 

In [80]:
feature_maps_bs = torch.Tensor([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])  
feature_maps_bs = feature_maps_bs.unsqueeze(1)
print(feature_maps_bs[0])

bn = nn.BatchNorm2d(num_features=1, momentum=0.3)
bn(feature_maps_bs)

tensor([[[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]]])


tensor([[[[-1.4142, -0.7071,  0.0000,  0.7071,  1.4142],
          [-1.4142, -0.7071,  0.0000,  0.7071,  1.4142],
          [-1.4142, -0.7071,  0.0000,  0.7071,  1.4142]]],


        [[[-1.4142, -0.7071,  0.0000,  0.7071,  1.4142],
          [-1.4142, -0.7071,  0.0000,  0.7071,  1.4142],
          [-1.4142, -0.7071,  0.0000,  0.7071,  1.4142]]]],
       grad_fn=<NativeBatchNormBackward>)

In [81]:
print(bn.running_mean) 
bn.running_var

tensor([0.9000])


tensor([1.3207])

In [43]:
os.makedirs("images", exist_ok=True)
parser = argparse.ArgumentParser()
parser.add_argument("--n_epochs", type=int, default=100, help="number of epochs of training")
#parser.add_argument("--batch_size", type=int, default=128, help="size of the batches")

_StoreAction(option_strings=['--n_epochs'], dest='n_epochs', nargs=None, const=None, default=100, type=<class 'int'>, choices=None, help='number of epochs of training', metavar=None)

In [87]:
    batch_size = 3
    num_features = 3
    momentum = 0.3

    features_shape = (2, 2)

    feature_map = torch.ones(features_shape)                                                    # 2D
    feature_maps = torch.stack([feature_map*(i+1) for i in range(num_features)], dim=0)         # 3D
    feature_maps_bs = torch.stack([feature_maps for i in range(batch_size)], dim=0)             # 4D

    #print(feature_maps_bs)
    print(feature_maps_bs.shape)
    # print("input data:\n{} shape is {}".format(feature_maps_bs, feature_maps_bs.shape))

    bn = nn.BatchNorm2d(num_features=num_features, momentum=momentum)

    running_mean, running_var = 0, 1

    for i in range(2):
        outputs = bn(feature_maps_bs)
        print('-'*19)
        print(outputs.shape)
        print("\niter:{}, running_mean: {}".format(i, bn.running_mean))
        print("iter:{}, running_var: {}".format(i, bn.running_var))

        print("iter:{}, weight: {}".format(i, bn.weight.data.numpy()))
        print("iter:{}, bias: {}".format(i, bn.bias.data.numpy()))

SyntaxError: invalid syntax (Temp/ipykernel_13688/3710638433.py, line 21)